Exception while resolving variable 'q' in template 'home.html'.
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'QueryDict' object has no attribute 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [q] in <QueryDict: {}>
Exception while resolving variable 'q' in template 'subscription/list.html'.
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'QueryDict' object has no attribute 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [q] in <QueryDict: {}>
Exception while resolving variable 'q' in template 'subscription/detail.html'.
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'QueryDict' object has no attribute 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [q] in <QueryDict: {}>
Exception while resolving variable 'authenticated' in template 'subscription/detail.html'.
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'authenticated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 835, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'authenticated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'authenticated'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [authenticated] in [{'True': True, 'False': False, 'None': None}, {'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x7f9db0bbfe50>>, 'request': <WSGIRequest: GET '/subscriptions/web-harvest/'>, 'user': <SimpleLazyObject: <User: andre@blackmesanetwork.com>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f9db0bb0520>, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f9db268d310>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'WARNING': 30, 'ERROR': 40}}, {}, {'object': <Subscription: Web Harvest>, 'subscription': <Subscription: Web Harvest>, 'view': <subscription.views.SubscriptionDetailSlugView object at 0x7f9db268dfa0>, 'ascii_art': '\n+---...-/`  /ddddhyyyyhhyyyyyyys+ooo+:::..---..``..--..``----..::::++shyyo+yyyyyyyhyyyyyyhhhhhhhh+`.\n/o/-..--`  .hhhhyhhyyyyhhys+ss+/:-..---.```````````..``````````..--..:+yooshyyys+yhyyyyyyhhhhhhhh/`.\n-:/...`  `:yyyyhhyosyhyyy+::-.-..`````````````````````````````````.`..oss:.:osyooyhhhyyoyhyyyhhhhs`.\n       ./syyssyyyhhysos+:--````````    ```       ```    ```` ```````./ys-...::/+oyhyyyyhhyyyyyyhhh:.\n++++oshdhhhysoyyyyy+:.....`` ```                 `       `      ````-ss-`.``.--..:oyyoshhhhyyhdhhhh-\nddddddhysshyhsssso:-.````````````                `             ```-+yyo.```````..-:/oohhhhhyyhhyyyhh\ndddddyyyssyhhyo/--.````````````     `            `             ``-yhyo/````  ```.`--::/shyyhdhhyyyyy\ndddhyhhooyyyyo:-.```````  ```                                  ``/hh++.````  ````````.-/+ysyhhhhyyhh\nddhssyhhhss+/-.`                                               `.yddhy. ``  ``````````-::/+yhhyhhyhh\ndhsoosyyyo/..`       `                                         .yddddho`    ``````` ``.....:sysyhhhy\nysyssyyyy:...`                                                `yddddddh/     `````````````.:/oyyhhhh\nsyyyyso/-```./+:`                                           ``sddddddddo           ````````-::+hhyyh\noosyyo/..``````-+o/.                                       ``sddhmmddddy            ````````..-oyhsh\noosys+-.``   `````-+s+.`                    `.---`        ``oddhdmmmmddy               ```````-:+hhh\nssso+-` ``      `````-+s+-`               `+hddddh+`     ``oddhdmmmmmmdh.              ``...```-:/hh\nhys+:`.` `        ``````-+o+-`           `ydddddddds` ````+dddhmmmmmmmmd-             ````.`.....-sh\nso+:-.``          `````````-/o+-`      ``/ddddmmmmmdo````+ddmmmmmmmmmddd.     ``      ``````.....:/y\no+/.``               `````````-/s/-` `..-/ddmmmmmmmmh:++sdddmmmmmmmmmmd:     `````` `````````.....-+\no+:``` `                   ``````./o+/:.--+dmmmmmmmmdmmddddmmmmmmmmmmd/     ``````````````````...---\n//-.````                       `````-+yho:.:sdmmmmmmmmmmmmmmmmmmmmmmdo      ```````````````````...-+\n--`  ```                          ```:ooshhs/:+dmmmmmmmmmmmmmmmmmmmy.``   ``````````````````````..-/\n--`` ````                            `-+yyyyddmmmmmmmmmmmmmmmmmmmmm+```   ``````````````````````....\n/-````   `                             `.:+ymmmmmmmmmmmmmmmmmmmmmmmd.            ````````````````...\n--.````````````  ```                    `.+hmmmmmmmmmmmmmmmmmmmmmmmms`         `````````````````...-\n..`  `  ```     `                      `.odmmmmmmmmmmmmmmmmmmmmmmmmmdy.              ```````````````\n-.````````````````````````````````````.-+dmmmmmmmmmmmmmmmmmmmmmmmmmmmdy` ` ```````````````````````..\n-.```       ` `                      `-/dmmmmmmmmmmmmmmmmmNNmmmmmmmmmmd:                   ````````.\n```` `                              `-:ymmmmmmmmmmmNmmmNmmmNmNmmmmmmmmdo                        ````\n``````         `    `              `:/sdmmmmmmmmmmmmNNNmmmmmmmNmmmmmmmmh:\n/-.``  ``           `` `   `     ``-/hmmmmmmmmmmddmNNNNNNNNmNNNmmmmmmmmmdo                        `.\n:````    `` `     ````````````` ``-+hmmmmmmmmmmmhhhdmNNNmmmmNmNNNmmmmmmmmdo`                   ````-\n.`  `` ` ````````````````````````:sdmmmmmmmmmmmdhyyshNNNNmNNNNmNmNmmmmmmmmds`                  ````-\n````````````````````````````````:sdmmmmmmmmmmmddyyysdNNNNNNNNNmNNmmmmmmmmmmd+         `         `../\n-s+```````````````````````````./ydmmmmmmmmmmh/yhyyhydNNNNNNNNNNmNNNmmmmmmmmmd+       ```` `     ..::\n/-`` ````````````````````````.ohdmmmmmmmmmms-.:ohhmmNNNNNNNNNNNmNNNmmmmmmmmmmdo                 `---\n```` `-:-..`````````````````-yddmmmmmmmmmd/..-+yhmNNNNmNmmmNmNNmNNNmmmmmmmmmmdd:               `-::/\n`.-`:o:::-.```````````````.+oddmmmmmmmmdo-...:sdmmNmNNmmmNNmmmmmNNNmmmmmmmmmmmds              .--:/+\ns./o//.`-:.``````````````.:yhdmmmmmmdh/....-+ydmmNNNNmNmmmmmmmmmNmNmmmmmmmmmmmdh`            `.--:::\ndy:`...``-//...`.````..../ydddddddhy/-....-ohmmmmNNNNNNNmmmmmmmmdyhhmmmmmmmmmmdy`          `.--/+/:-\nddy-  ``:+:/::-....```..:hddh++oo:---...-+shmmmmmNNNNNNNmmmmmmmdyysoodmmmmmmmmd-          ..`.-+yo//\ndddh+`/+/+.``.--...``..+hhs/...------..-oyhmmmmmNNNNNNmmmmmmmmdhyysso++dmmmmmmdy`       `....-://++o\nddddhy-::.```./o::-..:yho-......------:ohmmmmmmmmmmNNmmmmmmdooyyyyso+///smmmmmmd:     ```..:+:::---o\nddddddh+`  -:sysoo/:ohs:.........----/sdmmmmmmmmmmmmNmmmmmy-..-:osso+/::+mmmmmmdo   ` `  `-:s///::yd\nddddddddy:.:oyoo+++oso/:.--......--:oyhmmmmmmmmmNNNNmmmmy:.......-/o+/:+mmmmmmmds ````.``--:-::+oddd\nddddddddddy:::/osooyyoso/:--------/yhmmmmmmmmNNNNNNmmmd/...........:+/+mmmmmmmmdh.  `.oo`:...-ohdddd\nddddddddddddy/-:+shdhso+oyso+/--:+yhmmmmmmmmmNNNmmmmd+.............:++dmmmmmmmmmd+ ``.--/:/:shdddddd\nddddddddddddddho+syhyys++shyyy+/oyhmmmmmmmmmmNNmmmmo-.............:o+/dmmmmmmmmmdy``...`-syhdddddddd\nmddmmmdddddddddddys/+sosyhdysssydhdmmmmmmmmmmmmmmo-`....````.....-+/:.`/hmmmmmmmds:/-`:ohddddddddddd\n', 'cart': <Cart: 346>, 'subscription_slug': 'web-harvest', 'detail_url': 'subscription/snippets/web-harvest.html'}, {'block': <Block Node: content. Contents: [<TextNode: '\n\n<p style="font-family: '>, <Variable Node: object.title>, <TextNode: '</h4><br/> -->\n          '>, <Variable Node: object.timestamp |timesince>, <TextNode: ' ago.</h2><br/> -->\n     '>, <Variable Node: object.description>, <TextNode: '<br/> -->\n            '>, <django.template.loader_tags.IncludeNode object at 0x7f9db0bd4820>, <TextNode: '\n            \n           '>, <IfNode>, <TextNode: '\n        </div>\n\n        '>, <django.template.loader_tags.IncludeNode object at 0x7f9db0bd30a0>, <TextNode: '\n                    <div'>]>}, {'home_url': '/webharvest/'}]
Exception while resolving variable 'q' in template 'webharvest/home.html'.
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 837, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'QueryDict' object has no attribute 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 843, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'q'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/template/base.py", line 848, in _resolve_lookup
    raise VariableDoesNotExist("Failed lookup for key "
django.template.base.VariableDoesNotExist: Failed lookup for key [q] in <QueryDict: {}>
Not Found: /wss
Internal Server Error: /webharvest/api/v1/message/
Traceback (most recent call last):
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/home/ubuntu/stringkeeper/core/serializers.py", line 43, in create
    msg.save()
  File "/home/ubuntu/stringkeeper/core/models.py", line 61, in save
    self.notify_ws_clients()
  File "/home/ubuntu/stringkeeper/core/models.py", line 44, in notify_ws_clients
    channel_layer = get_channel_layer()
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/channels/layers.py", line 363, in get_channel_layer
    return channel_layers[alias]
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/channels/layers.py", line 80, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/channels/layers.py", line 46, in make_backend
    return self._make_backend(name, config)
  File "/home/ubuntu/stringkeeper/lib/python3.8/site-packages/channels/layers.py", line 61, in _make_backend
    raise InvalidChannelLayerError(
channels.exceptions.InvalidChannelLayerError: ROUTING key found for default - this is no longer needed in Channels 2.
